default_install_hook_types:
  - pre-commit

repos:
- hooks:
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
